const mutualFundConstants = {
    FETCH_MUTUAL_FUNDS_LIST_START: 'FETCH_MUTUAL_FUNDS_LIST_START',
    FETCH_MUTUAL_FUNDS_LIST_SUCCESS: 'FETCH_MUTUAL_FUNDS_LIST_SUCCESS',
    FETCH_MUTUAL_FUNDS_FAILURE: 'FETCH_MUTUAL_FUNDS_FAILURE',
    FETCH_MUTUAL_FUNDS_DETAILS_START: 'FETCH_MUTUAL_FUNDS_DETAILS_START',
    FETCH_MUTUAL_FUNDS_DETAILS_SUCCESS: 'FETCH_MUTUAL_FUNDS_DETAILS_SUCCESS',
}

export default mutualFundConstants;